import { Vazirmatn } from "next/font/google";
import AppProviderComponent from "@/components/providers/app/app-provider.component";

const vazir = Vazirmatn({ subsets: ['arabic'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: JSX.Element }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazir.className}>
        <AppProviderComponent>{children}</AppProviderComponent>
      </body>
    </html>
  );
}
